pub fn generate_task_json_content() -> String {
  return format!(r#"
  {{
  "tasks": [
    {{
      "type": "cppbuild",
      "label": "C/C++: g++.exe build active file",
      "command": "g++",
      "args": [
        "-fdiagnostics-color=always",
        "-g",
        "${{file}}",
        "-o",
        "${{fileDirname}}\\bin\\${{fileBasenameNoExtension}}.exe"
      ],
      "options": {{
        "cwd": "${{fileDirname}}"
      }},
      "problemMatcher": [
        "$gcc"
      ],
      "group": {{
        "kind": "build",
        "isDefault": true
      }},
      "detail": "Task generated by Debugger."
    }}
  ],
  "version": "2.0.0"
}}

  "#)
}
